version: '4.1'
services:
  pythonsdkdemo:
    stdin_open: true
    tty: true
    container_name: dstack-python-sdk-demo
    volumes:
      - ..:/usr/share/rtldev-middleware-python-sdk-demo:cached
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_MIN_VERSION: 3