name: Dependabot auto-merge
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    permissions:
      contents: read

  dependabot:
    name: Auto-merge Dependabot PR
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    needs: tests
    permissions:
      contents: write
      pull-requests: write

    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        # (fixes, features but not major upgrades!)
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}