name: Release
on: [push, pull_request]

jobs:
  test:
    name: Test Job
    # Support [skip ci] out of box with github actions Workaround
    # Only works for push https://github.com/actions/runner/issues/774
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(toJson(github.event.commits), '[skip ci]') == false)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip -V
          pip install -r requirements.txt
      - name: Run App
        run: python app.py
